openapi: 3.0.0
info:
  title: booking
  version: 1.0.0
paths:
  /bookings:
    get:
      summary: Get all bookings
      responses:
        '200':
          description: A list of bookings
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Booking'
        '500':
          description: Unable to retrieve bookings
    post:
      summary: Create a new booking
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Booking'
      responses:
        '201':
          description: Booking created
        '400':
          description: Invalid input
        '500':
          description: Unable to create booking
  /booking/{id}:
    get:
      summary: Get a booking by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Booking details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'
        '404':
          description: Booking not found
        '500':
          description: Unable to retrieve booking
    delete:
      summary: Delete a booking by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Booking deleted
        '404':
          description: Booking not found
        '500':
          description: Unable to delete booking
  /booking:
    get:
      summary: Get a booking by flight number and customer ID
      parameters:
        - name: flightNumber
          in: query
          required: true
          schema:
            type: string
        - name: customerId
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Booking details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'
        '404':
          description: Booking not found
        '500':
          description: Unable to retrieve booking
components:
  schemas:
    Booking:
      type: object
      properties:
        id:
          type: string
        flightId:
          type: string
        customerId:
          type: string
        date:
          type: string