openapi: 3.0.0
info:
  title: flight
  version: 1.0.0
paths:
  /flights:
    get:
      summary: Get all flights
      responses:
        '200':
          description: A list of flights
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Flight'
        '500':
          description: Unable to retrieve flights
    post:
      summary: Create a new flight
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Flight'
      responses:
        '201':
          description: Flight created
        '400':
          description: Invalid input
        '500':
          description: Unable to create flight
  /flight/{id}:
    get:
      summary: Get a flight by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Flight details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Flight'
        '404':
          description: Flight not found
        '500':
          description: Unable to retrieve flight
    delete:
      summary: Delete a flight by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Flight deleted
        '404':
          description: Flight not found
        '500':
          description: Unable to delete flight
components:
  schemas:
    Flight:
      type: object
      properties:
        id:
          type: string
        number:
          type: string
        carrier:
          type: string
        origin:
          type: string
        destination:    
          type: string
        departure:  
          type: string
        arrival:    
          type: string
        price:
          type: number