apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: accounts-statestore
spec:
  type: state.azure.cosmosdb
  version: v1
  metadata:
    - name: url
      secretKeyRef:
        name: cosmosDbUrl
        key: cosmosDbUrl
    - name: masterKey
      secretKeyRef:
        name: cosmosDbMasterKey
        key: cosmosDbMasterKey
    - name: database
      value: accounts
    - name: collection
      value: default
auth:
  secretStore: azurekeyvault
